@echo off

set mc_bin="C:\Program Files (x86)\Windows Kits\8.1\bin\x64\mc.exe"
set rc_bin="C:\Program Files (x86)\Windows Kits\8.1\bin\x64\rc.exe"
REM set mypath=""

set basedir=%cd%

cls
echo.
REM - cd /D %mypath%

echo.
echo - Compile message text file...
%mc_bin% a6oEventProvider.mc

echo.
echo - Compile resources generated by the compiler...
%rc_bin% a6oEventProvider.rc


echo.
echo - Create a resource only DLL...
link -dll -machine:x64 -noentry a6oEventProvider.res
echo.

echo - Clean directory...
del MSG00409.bin a6oEventProvider.rc a6oEventProvider.res
cd /D %basedir%
echo.