@echo off

set mc_bin="C:\Program Files (x86)\Windows Kits\8.1\bin\x64\mc.exe"
set rc_bin="C:\Program Files (x86)\Windows Kits\8.1\bin\x64\rc.exe"
set mypath="D:\Novit\uhuru-av\libuhuru\src\windows\service\MessageText"

set basedir=%cd%

cls
echo.
cd /D %mypath%

echo.
echo - Compile message text file...
%mc_bin% uhEventProvider.mc

echo.
echo - Compile resources generated by the compiler...
%rc_bin% uhEventProvider.rc


echo.
echo - Create a resource only DLL...
link -dll -machine:x64 -noentry uhEventProvider.res
echo.

echo - Clean directory...
del MSG00409.bin uhEventProvider.rc uhEventProvider.res
cd /D %basedir%
echo.