BINS=rpc-server-test rpc-client-test rpc-client-benchmark ptrarray-test
CFLAGS=-Wall -Wno-unused -I../include/ -I.. -DHAVE_PTHREAD
ifdef debug
CFLAGS+=-g -DDEBUG
endif
LDLIBS=-lm -lpthread 
OBJS=../buffer.o ../hash.o ../brpc.o ../ptrarray.o unix.o

all: $(BINS)

$(BINS): $(OBJS)

clean:
	-rm $(OBJS) $(BINS)
