#! /bin/bash
### BEGIN INIT INFO
# Provides:          uhuru-scand
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Uhuru antivirus scan daemon
# Description:       Debian init script for the Uhuru antivirus
#                    scan daemon
### END INIT INFO
#
# Author:	François Déchelle <francois@dechelle.net>
#

if [[ $EUID -ne 0 ]];
then
	echo "This script must be executed as root."
	exit 1;
fi

DAEMON=/usr/sbin/uhuru-scand
PIDFILE=/var/run/uhuru-scand.pid

test -x $DAEMON || exit 0

if test -f /etc/default/uhuru-scand-def; then
    . /etc/default/uhuru-scand-def
fi

. /lib/lsb/init-functions

set -e

echo "Starting $DEAMON $DAEMON_OPTS..."

case "$1" in
  start)
	log_daemon_msg "Starting Uhuru antivirus scan daemon" "uhuru-scand"
	start_daemon -p $PIDFILE $DAEMON $DAEMON_OPTS
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping Uhuru antivirus scan daemon" "uhuru-scand"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON uhuru-scand && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/uhuru-scand {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
