#include <libjrpc/marshall.h>

/* for testing */

JRPC_STRUCT(cplx)
	JRPC_STRUCT_FIELD_INT(int, re)
	JRPC_STRUCT_FIELD_INT(int, im)
JRPC_STRUCT_END

JRPC_ENUM(op_type)
	JRPC_ENUM_VALUE(OP_INT)
	JRPC_ENUM_VALUE(OP_CPLX)
	JRPC_ENUM_VALUE(OP_VCPLX)
JRPC_ENUM_END

JRPC_UNION(u_operand)
	JRPC_UNION_FIELD_INT(int, i_op, OP_INT)
	JRPC_UNION_FIELD_STRUCT(cplx, c_op, OP_CPLX)
	JRPC_UNION_FIELD_PTR_ARRAY(cplx, v_op, OP_VCPLX)
JRPC_UNION_END

JRPC_STRUCT(operands_with_union)
	JRPC_STRUCT_FIELD_ENUM(op_type, opt)
	JRPC_STRUCT_FIELD_UNION(u_operand, op1, opt)
	JRPC_STRUCT_FIELD_UNION(u_operand, op2, opt)
	JRPC_STRUCT_FIELD_UNION(u_operand, result, opt)
JRPC_STRUCT_END

JRPC_STRUCT(operands)
	JRPC_STRUCT_FIELD_ENUM(op_type, opt)
	JRPC_STRUCT_FIELD_INT(int, i_op1)
	JRPC_STRUCT_FIELD_INT(int, i_op2)
	JRPC_STRUCT_FIELD_INT(int, i_result)
	JRPC_STRUCT_FIELD_STRUCT(cplx, c_op1)
	JRPC_STRUCT_FIELD_STRUCT(cplx, c_op2)
	JRPC_STRUCT_FIELD_STRUCT(cplx, c_result)
	JRPC_STRUCT_FIELD_PTR_ARRAY(cplx, v_op1)
	JRPC_STRUCT_FIELD_PTR_ARRAY(cplx, v_op2)
	JRPC_STRUCT_FIELD_PTR_ARRAY(cplx, v_result)
JRPC_STRUCT_END

JRPC_STRUCT(notify_action)
	JRPC_STRUCT_FIELD_STRING(whot)
JRPC_STRUCT_END
