#include <libjrpc/marshall.h>

/* for testing */

JRPC_DEFINE_STRUCT(cplx)
	JRPC_DEFINE_FIELD_INT(int, re)
	JRPC_DEFINE_FIELD_INT(int, im)
JRPC_END_STRUCT

JRPC_DEFINE_ENUM(op_type)
	JRPC_DEFINE_ENUM_VALUE(OP_INT)
	JRPC_DEFINE_ENUM_VALUE(OP_CPLX)
JRPC_END_ENUM

JRPC_DEFINE_STRUCT(operands)
	JRPC_DEFINE_FIELD_ENUM(op_type, opt)
	JRPC_DEFINE_FIELD_INT(int, i_op1)
	JRPC_DEFINE_FIELD_INT(int, i_op2)
	JRPC_DEFINE_FIELD_INT(int, i_result)
	JRPC_DEFINE_FIELD_STRUCT(cplx, c_op1)
	JRPC_DEFINE_FIELD_STRUCT(cplx, c_op2)
	JRPC_DEFINE_FIELD_STRUCT(cplx, c_result)
	JRPC_DEFINE_FIELD_ARRAY(cplx, v_op1)
	JRPC_DEFINE_FIELD_ARRAY(cplx, v_op2)
	JRPC_DEFINE_FIELD_ARRAY(cplx, v_result)
JRPC_END_STRUCT
